name: 🐛 Bug Report
description: Report a bug or issue
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue! Please fill in the following information as detailed as possible to help us resolve the problem faster.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please clearly and concisely describe the issue you encountered
      placeholder: e.g., The application crashed when trying to mount an NTFS device
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please describe in detail how to reproduce this issue
      placeholder: |
        1. Open the application
        2. Insert an NTFS device
        3. Click the "Mount as Read-Write" button
        4. See error message
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The device should be successfully mounted in read-write mode
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The application displayed an error message "Mount failed"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: macOS Version
      description: The macOS version you are using (minimum macOS 14)
      options:
        - macOS 14 (Sonoma)
        - macOS 15 (Sequoia)
        - macOS 26
        - macOS 26+
        - Newer version
    validations:
      required: true

  - type: dropdown
    id: app_version
    attributes:
      label: Application Version
      description: The application version you are using (if using Electron version)
      options:
        - Latest version
        - Version from tags
        - Shell version (nigate)
        - Development version
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies Status
      description: Please check and list the installation status of dependencies (Swift, Homebrew, MacFUSE, ntfs-3g)
      placeholder: |
        - Swift: ✅ Installed
        - Homebrew: ✅ Installed
        - MacFUSE: ❌ Not installed
        - ntfs-3g: ✅ Installed

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If you have error logs or console output, please paste them here
      placeholder: Paste error logs or screenshots
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be useful (screenshots, device information, etc.)
      placeholder: e.g., The device uses Fast Startup feature in Windows

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and confirmed this is a new issue
          required: true
        - label: I have read the troubleshooting section in README
          required: false
        - label: I have tried reinstalling dependencies
          required: false
