blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/hoochanlon/Free-NTFS-for-Mac/discussions
    about: Ask general questions or participate in discussions.
  - name: 📖 Documentation
    url: https://github.com/hoochanlon/Free-NTFS-for-Mac/wiki
    about: View project documentation and usage instructions.
